test

diff --git a/.github/workflows/ci.helm-lint.yaml b/.github/workflows/ci.helm-lint.yaml
--- a/.github/workflows/ci.helm-lint.yaml
+++ b/.github/workflows/ci.helm-lint.yaml
@@ -27,4 +27,20 @@ jobs:
       - name: Run Helm lint
         uses: WyriHaximus/github-action-helm3@v3
         with:
-          exec: find . -name 'Chart.yaml' -exec dirname {} \; | xargs -I {} helm lint {} | grep "failed" && exit 1 || exit 0
+          exec: |
+            failed_services=""
+            for file in $(git diff --name-only HEAD~1..HEAD); do
+              dir=$(dirname $file)
+              if [ -f "$dir/Chart.yaml" ]; then
+                if ! helm lint $dir; then
+                  echo "'$(basename $dir)' failed"
+                  failed_services+="'$(basename $dir)', "
+                fi
+              fi
+            done
+
+            if [ -n "$failed_services" ]; then
+              # Remove the trailing comma and space
+              failed_services=${failed_services%??}
+              echo "Lint failed services: $failed_services"
+            fi
